### ISSUE TITLE
Latest version kills lots of functions of TabMixPlus

### ISSUE THREAD

**Issue by ikrg666** [gantt/downloadyoutube#103]
I am using your add-on for a long time. But 
the latest version  1.8.10 kills many functions of the TabMixPlus add-on version 0.4.1.5.2.1-signed.
I am using Firefox 28.0 with the compatible TabMix version 0.4.1.5.2.1-signed and "Download YouTube Videos as MP4" 1.8.10.
Tested on a new and clean Firefox 28 profile wit just those two addons installed, no other modifications!
Without your addon everything works fine, but otherwise:
TabMixPlus function "Duplicate tab" does not work (creates empty tab)
TabMixPlus function "Closed tab list" is always empty
TabMixPlus function "Session restore" does not work

**Comment by gantt** [comment]
Hello

I have never used the extension you mentioned until today and never tested the compatibility with other extensions, mostly because my extension is extremely basic and it shouldn't interfere with other extensions. It only injects some code in youtube.com pages and that's all.

I tested TabMixPlus (version 0.5.0.2 in Firefox 52 for Mac) and "duplicate tab" and "closed tab list" feature work fine for some random YouTube videos I tested. You're using old versions of Firefox and TabMixPlus, while I tested the latest versions. I don't know how TabMixPlus works, but I don't see how a Greasemonkey-like extension can interfere with the features you mentioned.

**Comment by ikrg666** [comment]
Hello Gant,

thanks for your quick answer.
Well, I know sometimes there are really strange issues, I am FF addon 
developer myself.

But I just confirmed the issues again, and they are definately caused by 
your addon.
However, I was wrong with the version of your addon:
Whereas Version 1.8.7 still works fine with TabMix, the next version 
1.8.8 (and later) does not.

Thus one of these modifications seem to cause the issue:
* Removed outdated formats
* Fixed manifest parsing (thanks, Elite2016)

Please note:
Though your addon is restartless, it needs a full FF restart to show the 
issue! That's at least necessary with the old versions I am using.

Thanks,
Ingo

**Comment by ikrg666** [comment]
I could strip down the problem to overlay.js.
Version 1.8.10 with overlay.js of v. 1.8.7 stops the issue.
However,I suppose v. 1.8.10 won't work with the old overlay.

**Comment by ikrg666** [comment]
Well, file comparison of overlay.js did not show any important 
modifications.

Just definitions of Cu, Ci and similar.
Strange but true, exactly this is the culprit.

Using the former long names fixes the issues.
Thus I could solve the problem myself.
Anyway thanks for your efforts.

Please consider the necessary modifications with your next update.
Still cannot explain what's going wrong there, but to find the real 
reason would need to analyze the TabMixPlus  addon.
Too much effort even for 2 of us, you agree?

**Comment by gantt** [comment]
OK, I'll check it out. Thanks for letting me know about this.

**Comment by ikrg666** [comment]
Thanks,
just tested v. 1.8.10 (original) with latest FF and latest TabMix.
With the latest versions no problems.

Thus only me and possibly a very few users with old versions are affected.
Nothing to worry about.
I now know how to fix it easily.

**Comment by ikrg666** [comment]
If you can find the reason for the issue, please let me know.
Defining those constants should change nothing, and should not affect 
other addons at all.
