### ISSUE TITLE
Question: how to enable download M4A audio on Chrome/Opera?

### ISSUE THREAD

**Issue by 0xh3LL0** [gantt/downloadyoutube#105]
on firefox, we can just simply go to about:config and change the youtube dash enable to 1
but how to enable it on chrome/opera?

**Comment by gantt** [comment]
Right click a YouTube page, select "inspect element", go to the console and paste this line:
window.localStorage["download-youtube-dash-enabled"]=1
Then press Enter.

To disable Dash, paste
window.localStorage["download-youtube-dash-enabled"]=0
