### ISSUE TITLE
closed caption issue

### ISSUE THREAD

**Issue by jeffeyer** [gantt/downloadyoutube#31]
Hello gantt,

You have a great program for us to use your downloadyoutube software.  Thank you.

Unfortunately, your software is missing - the most important is the closed captions.  When I downloaded several video clips on my hard disk drive, then I clicked to watch the clips and I do not see any closed captions.  I am deaf.  I am sure that many of us want to have them captioned.

Please be kind that you need to comply the FCC policy.  If you don't believe me, here is the link:
http://transition.fcc.gov/cgb/consumerfacts/closedcaption.pdf

Beside, I would love to watch the captions on the video clips that I missed the most.  Imagine that you are deaf, too.  Please just think about it.  Enjoy your day!

**Comment by gantt** [comment]
I'm sorry, but captions aren't part of the video. They're separate text files. I could add the option to download subtitles, but only as a separate file.

I didn't want to deal with captions because:

1. Most videos don't have captions
2. Not many people want this feature
3. Some videos have multiple captions in different languages and I would have to add a list of options
4. Not all video players handle YouTube subtitles properly

**Comment by jeffeyer** [comment]
Hello gantry,

Thank you for the reply.  Would it be a possible for to contact the YouTube Company to preserve the closed caption space in the video source codes so that you would not need to add your own codes in your program?  For example, the sound codes are already added on the YouTube program permanently.  That leave one more is the captions.  It does not matter if the person didn't put their captions that will leave it off unless there is on the CC button on the screen.

It's because the YouTube must comply the FCC law.  You know the YouTube has billions of dollars, and they have to do it anyway no matter what.  There are a few thousands of employees that work for the YouTube Company.  Right?   Also what are they doing now at the company? Nothing and just slow down and easy work that leave one thing that does not work with downloading video clips for the captions.  Oh the captions are supposed to be added a long time ago.  ...There are three bars (bottom) on old film that are video, sounds, and (in fact) captions.

You need to push the YouTube to do it.  Just remind you that how you feel that you are deaf.  (...Even elders will be deaf, too. Being deaf that change your life little hard to deal with the hearing world.)

Thanks again.  Jeff
