### ISSUE TITLE
Can't download video

### ISSUE THREAD

**Issue by apaket** [gantt/downloadyoutube#32]
Can't download from this URL: http://www.youtube.com/watch?v=G49KeoYMjcg&index=4&list=PL7D37F0D7160E15F8

**Comment by gantt** [comment]
It uses rtmp streams and can't be downloaded using this script.

http://en.wikipedia.org/wiki/Real_Time_Messaging_Protocol
http://en.wikipedia.org/wiki/Protected_Streaming
