### ISSUE TITLE
Again Not working , detecting null as the function name pls fix soon

### ISSUE THREAD

**Issue by fooble** [gantt/downloadyoutube#34]

**Comment by gantt** [comment]
Can you provide more details?

https://github.com/gantt/downloadyoutube/blob/master/Debug.md

**Comment by fooble** [comment]
It is working fine on chrome but not on firefox, and I aint got nightly version of firefox



"DYVAM - Info: Standard mode. videoID PK8dsAeMmPk;  DYVAM - Info: url https://www.youtube.com/watch?v=PK8dsAeMmPk; useragent Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0 DYVAM fetch https://s.ytimg.com/yts/jsbin/html5player-en_GB-vflaAfmBc/html5player.js DYVAM - Info: itag5 url:https://r2---sn-905qg5ou-qxal.googlevideo.com/videoplayback?mm=31&amp;ipbits=0&amp;dur=273.371&amp;fexp=900161,900718,907263,927622,930676,943917,947225,948124,952302,952605,952901,955301,957103,957201,959701&amp;id=o-AJxVDuB2nFtC7s6tgjQJCIyLQh07Fs0MwVLnVpwfkK26&amp;pl=21&amp;sver=3&amp;signature=F9BD4D4F3FAC4EA46E7ED054C7093245888F0794.F38768153C7A4DE4E8D22F7BE7CA36DCC18C988F&amp;expire=1422419901&amp;itag=5&amp;ip=125.62.122.38&amp;requiressl=yes&amp;initcwndbps=332500&amp;key=yt5&amp;mt=1422398276&amp;upn=LEH2z5Yypyc&amp;source=youtube&amp;sparams=dur,id,initcwndbps,ip,ipbits,itag,mime,mm,ms,mv,pl,requiressl,source,upn,expire&amp;mv=m&amp;mime=video/x-flv&amp;ms=au&amp;ratebypass=yes&amp;title=Rubber bands vs Water Melon - The Slow Mo Guys DYVAM - Info: itag18 url:https://r2---sn-905qg5ou-qxal.googlevideo.com/videoplayback?mm=31&amp;expire=1422419901&amp;id=o-AJxVDuB2nFtC7s6tgjQJCIyLQh07Fs0MwVLnVpwfkK26&amp;pl=21&amp;ip=125.62.122.38&amp;requiressl=yes&amp;mt=1422398276&amp;sparams=dur,id,initcwndbps,ip,ipbits,itag,mime,mm,ms,mv,pl,ratebypass,requiressl,source,upn,expire&amp;mv=m&amp;ms=au&amp;initcwndbps=332500&amp;upn=LEH2z5Yypyc&amp;source=youtube&amp;signature=0BEC2CBA5A915CB0F55E052E1562CF2DF7E9C888.C93DDB3D3554E736CB273E706C23383F1F7239E1&amp;itag=18&amp;mime=video/mp4&amp;key=yt5&amp;ipbits=0&amp;dur=273.368&amp;sver=3&amp;ratebypass=yes&amp;fexp=900161,900718,907263,927622,930676,943917,947225,948124,952302,952605,952901,955301,957103,957201,959701&amp;title=Rubber bands vs Water Melon - The Slow Mo Guys DYVAM - Info: itag22 url:https://r2---sn-905qg5ou-qxal.googlevideo.com/videoplayback?mm=31&amp;expire=1422419901&amp;id=o-AJxVDuB2nFtC7s6tgjQJCIyLQh07Fs0MwVLnVpwfkK26&amp;pl=21&amp;ip=125.62.122.38&amp;requiressl=yes&amp;mt=1422398276&amp;sparams=dur,id,initcwndbps,ip,ipbits,itag,mime,mm,ms,mv,pl,ratebypass,requiressl,source,upn,expire&amp;mv=m&amp;ms=au&amp;initcwndbps=332500&amp;upn=LEH2z5Yypyc&amp;source=youtube&amp;signature=3CCD88BA14F348FBC9F09DFB052220CF9938537E.5B1F596C8DADFE5FE5A3C8D7C33D9D846AEBCCB2&amp;itag=22&amp;mime=video/mp4&amp;key=yt5&amp;ipbits=0&amp;dur=273.368&amp;sver=3&amp;ratebypass=yes&amp;fexp=900161,900718,907263,927622,930676,943917,947225,948124,952302,952605,952901,955301,957103,957201,959701&amp;title=Rubber bands vs Water Melon - The Slow Mo Guys DYVAM fetch status 200 ***VISITOR_INFO1_LIVE=na8BEd0t01s"

**Comment by fooble** [comment]
i 've mailed you as well

**Comment by gantt** [comment]
You're using an old version of the script. I've tested the latest version
and it works fine.

On Wed, Jan 28, 2015 at 12:41 AM, Rahul Verma <notifications@github.com>
wrote:

> i 've mailed you as well
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gantt/downloadyoutube/issues/34#issuecomment-71743935>
> .
>



-- 
Ionut Alex Chitu
