### ISSUE TITLE
Using your extension with Tor browser

### ISSUE THREAD

**Issue by joey2u** [gantt/downloadyoutube#36]
It does not seem to work.
Any idea why?
Thanks.

**Comment by gantt** [comment]
Works for me.

![screen shot 2015-02-18 at 08 27 01](https://cloud.githubusercontent.com/assets/8141540/6243355/2ecefa2c-b748-11e4-990f-524a10fadec9.png)
![screen shot 2015-02-18 at 08 27 16](https://cloud.githubusercontent.com/assets/8141540/6243359/34ebb878-b748-11e4-8847-4ae3117d8ec9.png)

**Comment by joey2u** [comment]
I think the problem is that I use Tor in "safe mode" to provide higher security, which means with NoScript enabled. NoScript can prevent many kinds of attacks which originate from sites. So I can't use this extension, it seems. Oh, well - better to be safe than sorry for not being able to view some vids...
Joey2u

**Comment by gantt** [comment]
Why not add youtube.com to the whitelist? I assume you've disabled "scripts globally allowed". If youtube.com is not allowed to run scripts, YouTube's site is mostly unusable.

**Comment by joey2u** [comment]
Because youtube.com is Google. And I don't trust Google. There are a number of issues with Google's handling of their services, including Google's invasion of privacy (they read all your e-mail, and keep track of your browsing history, your contact history, etc.) and their penchant for cooperating with legal authorities on the basis of mere "suspicions". Using Google products means allowing Google to know virtually *everything* about you.
I don't want any corporation to know too much about me. And I mean *any* corporation - and that includes the government. George Orwell was right, you know, he just had the year wrong... 
So, no "white listing" of such an intrusive corporation for me, thank you!
There was another Firefox add-on that worked with the Tor version of Firefox, and with scripts disabled, but I don't remember what it was.
Any idea?

**Comment by gantt** [comment]
I have no idea. If you find it, please let me know. I'm curious if it's posible.
