### ISSUE TITLE
Ability to download playlists

### ISSUE THREAD

**Issue by AymanGaafar** [gantt/downloadyoutube#39]
Hi,

There is a software called freemake that has a YouTube download option. before they had this extension that integrated itself to YouTube and added the ability to download videos from any place (video page, playlist page, from home page, etc...). It would be very awesome if you could do the same since that is no longer available.

really appreciate the work done.

**Comment by gantt** [comment]
That might work as an extension, but not as a script. It's an advanced feature that would require a complicated interface and I don't know how many people would use it.
