### ISSUE TITLE
Can't download 2160p4k no-audio-video!

### ISSUE THREAD

**Issue by lindongbin** [gantt/downloadyoutube#40]
https://www.youtube.com/watch?v=l9m4cW2yxy0

Can only download the max 1440p no-audio-video.

**Comment by lindongbin** [comment]
this script has all formats
https://greasyfork.org/en/scripts/5566-youtube-links

**Comment by gantt** [comment]
Thanks for letting me know about this. Adding the itag=266 format seems to fix it, but I need to test this a little bit more.

**Comment by gantt** [comment]
For this video: https://www.youtube.com/watch?v=yO8Fn1OO3Q8 there are two 4K options available: one of them is already displayed by the script (itag=138), the other one is new (itag=266). One of the files has 128MB, the other one has 146MB.

**Comment by gantt** [comment]
It looks like the new 4K flavor has a higher bitrate. If both the new one and the old one are available, I'll only add the new one.

**Comment by lindongbin** [comment]
and the '141':'M4A 256kbps - audio' ??

**Comment by gantt** [comment]
For which video?

**Comment by lindongbin** [comment]
https://www.youtube.com/watch?v=l9m4cW2yxy0

**Comment by gantt** [comment]
![screen shot 2015-04-03 at 17 20 00](https://cloud.githubusercontent.com/assets/8141540/6983385/dc4e0e40-da25-11e4-9495-cf257706adc6.png)
