### ISSUE TITLE
Cannot install on Firefox 37 for android

### ISSUE THREAD

**Issue by wilfm** [gantt/downloadyoutube#41]
Trying to instantly the add-on for this extension from https://addons.mozilla.org results in a error that it has not been updated for Firefox 37 - the same error occurs when trying to install grease monkey to run the script.

I have had success using this on desktop Firefox and Firefox for android  (with desktop view enabled) in the past... Thank you!

**Comment by gantt** [comment]
The extension doesn't work for the mobile YouTube, it doesn't work for mobile Firefox and you wouldn't be able to install it from Mozilla's site (assuming that it would work) because Google Play forbids YouTube downloaders.

**Comment by gantt** [comment]
To sum up:

1. there are no user script extensions for mobile Firefox, so I haven't bothered to update the script to work for m.youtube.com. Even if the script worked, you wouldn't be able to run it, so what's the point?

2. Mozilla rejects extensions that download YouTube videos, but only if they work in Android, so I can't add Android compatibility for the extension.

**Comment by wilfm** [comment]
I have got it to work with mobile firefox using 'show as desktop' previously - this is to get around the fact that the youtube app can't play in the background but most video playing apps can - never mind, continue the good work :)
