### ISSUE TITLE
multiple popup of download toolbar of idm

### ISSUE THREAD

**Issue by rdexter** [gantt/downloadyoutube#42]
every time when i open a you tube video idm pop up of download occur of every format (like 720,480).i already try to restart of the firefox but same result. but work fine on gtml file as well as flash.please fix it.

![screenshot 1](https://cloud.githubusercontent.com/assets/11786849/6983789/ebb2235c-d9d6-11e4-82bf-d3ca89a3842a.png)

**Comment by gantt** [comment]
So what can I do about this? You're using a third-party software, which is probably buggy.

Did you try disabling IDM and downloading videos using Firefox's download manager?

**Comment by rdexter** [comment]
you are right.
