### ISSUE TITLE
No option for video download above 360p

### ISSUE THREAD

**Issue by fidorulz** [gantt/downloadyoutube#45]
Not sure whats going on but for the past few weeks no youtube video allows me to download above 360p via this extension

I know the videos have 1080p but the extension isn't showing download options

Is there something im doing causing this?

Im using firefox 37.0.2 on windows 8.1

**Comment by gaberad** [comment]
Look for a youtube cookie called VISITOR_INFO1_LIVE and delete it. That fixed it for me.

**Comment by fidorulz** [comment]
Thanks a million that fixed it. Was going insane trying to figure this one out
