### ISSUE TITLE
Resolution + Aspect ratio being changed to downloaded file?

### ISSUE THREAD

**Issue by krizman99** [gantt/downloadyoutube#50]
I'm trying to figure out what is going on for this situation.  Playing this Youtube video maximized next to another monitor with a maximized VLC file source and they look complete different, aspect ratio wise.  First I thought it was some VLC setting that was altering the aspect ratio.  I then used a MediaInfo program to analyze the video stream source file that I downloaded with your script.  It displays the following from the video source below.
https://www.youtube.com/watch?v=dQ4XHW5Q4gU

720p   = 1280 x 404
1080p = 1920 x 608
1440p = 2276 x 720 : 22.5MB
2160p = 2276 x 720 : 36.7MB

I'm assuming the Youtube video is playing at the typical:
1280 x 720
1920 x 1080
2560 x 1440
3840 x 2160

I'm just wondering why the downloaded content isn't the same or what is changing it and why?
Thanks.

**Comment by gantt** [comment]
Use "stats for nerds" (right click inside the player) and change resolutions from the settings button. Check these fields: dimensions (what's displayed) and resolutions (actual resolution, what you get when you download the video).

Example;

![screen shot 2015-06-25 at 16 05 23](https://cloud.githubusercontent.com/assets/8141540/8354887/2693d4de-1b54-11e5-9c57-52f4c0ffc3b0.png)

**Comment by krizman99** [comment]
Ok, so the Youtube source and downloaded source are the same.  Now would you be able to shed any light on why when the Youtube screen is maximized that it appears like a normal 1920x1080 resolution but the VLC appears more accurate like the 1920x608 it is indicated as?

Even when it is not maximized, you can see how its aspect ratio of Youtube is consistent with a 1.777 (1920x1080), where the source file is 3.161.

**Comment by gantt** [comment]
I'm not sure I understand your issue.

To watch the downloaded video in VLC like on YouTube, change the aspect ratio to 16:9 in the View menu. The video is intentionally distorted to look good at 16:9. It's not even an actual video: just a static picture and some music.

**Comment by krizman99** [comment]
Does Youtube play all videos with a forced aspect ratio of 16:9?  I just thought they played the source file aspect ratio, so I was surprised to see a difference on VLC.

**Comment by gantt** [comment]
Maybe the uploader used these tags:

http://youtube-global.blogspot.com/2009/04/release-notes-43009.html

**Comment by gantt** [comment]
Maybe the uploader used these tags:
http://youtube-global.blogspot.com/2009/04/release-notes-43009.html

On Thu, Jun 25, 2015 at 4:34 PM, krizman99 <notifications@github.com> wrote:

> Does Youtube play all videos with a forced aspect ratio of 16:9? I just
> thought they played the source file aspect ratio, so I was surprised to see
> a difference on VLC.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gantt/downloadyoutube/issues/50#issuecomment-115259958>
> .
>



-- 
Ionut Alex Chitu

**Comment by krizman99** [comment]
This makes more sense to what is going on.  Thanks for the insight.
