### ISSUE TITLE
MP4 portion is 2x'ed?

### ISSUE THREAD

**Issue by krizman99** [gantt/downloadyoutube#55]
This video downloaded fine the first time, then I reloaded the page and now it is showing up double in size and length.  The video is looped twice on the download.  Can you explain why this is happening, for personal enlightenment?  Thanks.

https://www.youtube.com/watch?v=Z-48u_uWMHY

**Comment by gantt** [comment]
It doesn't happen to me. Some screenshots and download URLs would be helpful. The script doesn't modify videos and in any way, so it's impossible to show the same video twice in the same file. The script only extracts URLs from the YouTube page.

**Comment by krizman99** [comment]
After looking at it again, the video wasn't 2x, but rather it shows 13:49 long and the scanning is messed up, yet it is still the original video excluding the stated duration and messed up scanning.  So 1 standard real time second, makes the video tick like 2-3 seconds.  The 1080p file shows 150.1MB, but the 132.3MB 720p file was fine.
![untitled](https://cloud.githubusercontent.com/assets/8921850/11023744/652b2f9c-864f-11e5-9b92-f9c937a980ca.jpg)
