### ISSUE TITLE
downloader suddenly fails on many videos

### ISSUE THREAD

**Issue by OrleonB** [gantt/downloadyoutube#59]
"Download Youtube Videos As Mp4" has long been working flawlessly for me.  Beginning November 9th, when I click my quality choice, a blank screen comes up instead of a save option box.  This is a widespread occurrence, although an exploration found that it is not universal.  

Here is a sample failure:

video address:  
https://www.youtube.com/watch?v=wflDii2RbVE

address when I choose quality:  
https://r4---sn-vgqs7ne6.googlevideo.com/videoplayback?dur=302.138&itag=22&pl=41&source=youtube&expire=1447176796&nh=IgpwcjAxLm9yZDEyKg8yNjEwOjE4OjEwZDo6NzU&lmt=1446962627610521&mime=video/mp4&requiressl=yes&gcr=us&fexp=9407118,9408500,9408710,9414764,9416126,9417529,9417683,9417707,9418200,9419444,9419837,9420453,9420539,9422151,9422288,9422596,9422618,9423645,9423662,9423667,9423789,9423819,9423851&ip=2604:6000:9fc0:2c:a1b9:66c4:3065:312a&key=yt6&mt=1447155157&mv=m&ms=au&mm=31&mn=sn-vgqs7ne6&id=o-APey3r0jXUkeYh8ZXiqbb9gtWHF8k4hHkWCS-lqcH3YU&upn=CxYf1HT0Idc&sparams=dur,gcr,id,initcwndbps,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,nh,pl,ratebypass,requiressl,source,upn,expire&sver=3&ratebypass=yes&ipbits=0&initcwndbps=672500&signature=C3EDC659A41B77AACEEC82C5721E164C56D708C9.11254F7A51940A448E7FE58570596E095009451951DD&title=Absolutely%20Sweet%20Marie%20%28Take%201,%20Alternate%20Take%29

**Comment by gantt** [comment]
Fixed in 1.8.4. Please update to the latest version.
