### ISSUE TITLE
can not show all m4a files

### ISSUE THREAD

**Issue by lindongbin** [gantt/downloadyoutube#62]
when I change 'm4a':'max' , there is 256k m4a file download
but change to 'm4a':'all', it only show 128k m4a download

**Comment by gantt** [comment]
You are absolutely right. I got lazy and only added support for 256kbps if the value is 'max'. Here's the updated version: https://www.dropbox.com/s/1t1p1nl21jv7io0/Download%20YouTube%20Videos%20as%20MP4.user.js?dl=0 

I haven't tested it properly, but hopefully it works properly.

**Comment by gantt** [comment]
It's worth pointing out that most (if not all) new videos only use 128kbps M4A audio and that's the one and only audio file.

**Comment by lindongbin** [comment]
thanks, it's working.
