### ISSUE TITLE
Only 360p MP4 in Firefox

### ISSUE THREAD

**Issue by clamsioPL** [gantt/downloadyoutube#63]
Why I can't download HD resolution?
Clear cookies don't help.
![IMAGE](https://cloud.githubusercontent.com/assets/7839556/11745875/45ef3dae-a01b-11e5-9223-37ba98eb1d70.png)

**Comment by gantt** [comment]
I don't know what else to suggest. I hope it's still a YouTube experiment.

![screen shot 2015-12-18 at 18 40 04](https://cloud.githubusercontent.com/assets/8141540/11901897/c66e8a70-a5b6-11e5-8865-fb7c58581310.png)
