### ISSUE TITLE
Firefox YouTube Downloads

### ISSUE THREAD

**Issue by TimboCD1** [gantt/downloadyoutube#64]
Every time I try to download a video it tries to open a link and crashes - example link

https://r3---sn-8pgbpohxqp5-h5os.googlevideo.com/videoplayback?id=o-AEV-ANG9bj8KyandCiVexnuw946Rh2V32koXDSrnTlmL&upn=nfi1aDBP8z0&initcwndbps=2628750&lmt=1405805850587562&ip=81.97.121.6&sparams=dur,id,initcwndbps,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,pl,ratebypass,requiressl,source,upn,expire&fexp=9408215,9410705,9414702,9416126,9417367,9420452,9421249,9422342,9422596,9423345,9423662,9423853,9425715,9425783&dur=228.600&sver=3&expire=1450473901&pl=22&ratebypass=yes&key=yt6&itag=18&ipbits=0&ms=au&mt=1450452183&mv=m&source=youtube&requiressl=yes&mime=video/mp4&mm=31&mn=sn-8pgbpohxqp5-h5os&signature=CFBAFB8F3B97EA29B66AA458C48ED05E5D060819346.9A65D6598127C33741C13BD79E00FACD4EEE1580580&title=Paloma%20Faith%20-%20Picking%20Up%20The%20Pieces%20%28Acoustic%20Session%29

**Comment by gantt** [comment]
Crashes? Maybe it opens a blank page.

That URL is not properly generated, the signature parameter is not valid, which means that it hasn't been decrypted. There are many reasons why this could happen:

1. YouTube changed the code
2. the JS file that includes the decryption function couldn't be read
3. YouTube's source code has invalid URLs
4. some other bugs

It would be helpful if you could send this debug info: https://github.com/gantt/downloadyoutube/blob/master/Debug.md

**Comment by gantt** [comment]
There is an issue with signature detection and I'll try to fix it.

**Comment by whodafly** [comment]
I'm getting this issue too, with some, but not all videos. Here's my debug output, if it helps:

    11:05:43.961 "DYVAM - Info: Standard mode. videoID xFDHug7B_LQ;  DYVAM - Info: url https://www.youtube.com/watch?v=xFDHug7B_LQ; useragent Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0 Iceweasel/38.3.0 DYVAM fetch https://s.ytimg.com/yts/jsbin/player-en_US-vflXJM_5_/base.js DYVAM - Info: itag5 url:https://r1---sn-hfxc-j2ul.googlevideo.com/videoplayback?sparams=dur,gcr,id,initcwndbps,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,pl,requiressl,source,upn,expire&amp;id=o-ANpa5umBrcQLUmRMBR3gK4IZzvCq0GkP-Pe2v4k5-pB8&amp;initcwndbps=307500&amp;ip=165.255.70.227&amp;requiressl=yes&amp;pl=24&amp;gcr=za&amp;expire=1450535944&amp;lmt=1386308144932326&amp;key=yt6&amp;itag=5&amp;mime=video/x-flv&amp;ipbits=0&amp;dur=223.086&amp;ms=au&amp;fexp=9408541,9416126,9417353,9418204,9420452,9420539,9422596,9423299,9423662,9424551,9424623,9424771,9425308,9425514,9426036&amp;mv=m&amp;mt=1450514205&amp;mn=sn-hfxc-j2ul&amp;mm=31&amp;source=youtube&amp;sver=3&amp;upn=yRJxfxpPyB4&amp;signature=FCD3CD0E8008638075061AF2D323FA736A2161CD75A.2F340371EBB60DE6B2DC321E571866CA42E830E40E4&amp;ratebypass=yes&amp;title=Owl City feat. TobyMac - Light of Christmas _ New Song 2013 DYVAM - Info: itag18 url:https://r1---sn-hfxc-j2ul.googlevideo.com/videoplayback?sparams=dur,gcr,id,initcwndbps,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,pl,ratebypass,requiressl,source,upn,expire&amp;id=o-ANpa5umBrcQLUmRMBR3gK4IZzvCq0GkP-Pe2v4k5-pB8&amp;initcwndbps=307500&amp;ip=165.255.70.227&amp;requiressl=yes&amp;pl=24&amp;gcr=za&amp;expire=1450535944&amp;mn=sn-hfxc-j2ul&amp;lmt=1417222227576870&amp;key=yt6&amp;itag=18&amp;mime=video/mp4&amp;ipbits=0&amp;dur=223.097&amp;ms=au&amp;fexp=9408541,9416126,9417353,9418204,9420452,9420539,9422596,9423299,9423662,9424551,9424623,9424771,9425308,9425514,9426036&amp;mv=m&amp;mt=1450514205&amp;ratebypass=yes&amp;mm=31&amp;source=youtube&amp;sver=3&amp;upn=yRJxfxpPyB4&amp;signature=26F46F360298341C1B928172C78C3D1D1ABFC1D8CDE.0D6988B31F4B16D2EAA408E54E99FC9D0673FFF6FF6&amp;title=Owl City feat. TobyMac - Light of Christmas _ New Song 2013 DYVAM - Info: itag22 url:https://r1---sn-hfxc-j2ul.googlevideo.com/videoplayback?sparams=dur,gcr,id,initcwndbps,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,pl,ratebypass,requiressl,source,upn,expire&amp;id=o-ANpa5umBrcQLUmRMBR3gK4IZzvCq0GkP-Pe2v4k5-pB8&amp;initcwndbps=307500&amp;ip=165.255.70.227&amp;requiressl=yes&amp;pl=24&amp;gcr=za&amp;expire=1450535944&amp;mn=sn-hfxc-j2ul&amp;lmt=1417222232096005&amp;key=yt6&amp;itag=22&amp;mime=video/mp4&amp;ipbits=0&amp;dur=223.097&amp;ms=au&amp;fexp=9408541,9416126,9417353,9418204,9420452,9420539,9422596,9423299,9423662,9424551,9424623,9424771,9425308,9425514,9426036&amp;mv=m&amp;mt=1450514205&amp;ratebypass=yes&amp;mm=31&amp;source=youtube&amp;sver=3&amp;upn=yRJxfxpPyB4&amp;signature=2A16A1233458C6149459D0BA36927641241B2C708BD.646027864979E328238304B1633C1141ECC88D3CD3C&amp;title=Owl City feat. TobyMac - Light of Christmas _ New Song 2013 DYVAM fetch status 200 DYVAM - Info: signature start error DYVAM - Info: signaturefunction gr -- null ***null"

**Comment by gantt** [comment]
It's only for music videos (Vevo and others).

On Saturday, December 19, 2015, Raoul Snyman <notifications@github.com>
wrote:

> I'm getting this issue too, with some, but not all videos. Here's my debug
> output, if it helps:
>
> 11:05:43.961 "DYVAM - Info: Standard mode. videoID xFDHug7B_LQ;  DYVAM - Info: url https://www.youtube.com/watch?v=xFDHug7B_LQ; useragent Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0 Iceweasel/38.3.0 DYVAM fetch https://s.ytimg.com/yts/jsbin/player-en_US-vflXJM_5_/base.js DYVAM - Info: itag5 url:https://r1---sn-hfxc-j2ul.googlevideo.com/videoplayback?sparams=dur,gcr,id,initcwndbps,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,pl,requiressl,source,upn,expire&amp;id=o-ANpa5umBrcQLUmRMBR3gK4IZzvCq0GkP-Pe2v4k5-pB8&amp;initcwndbps=307500&amp;ip=165.255.70.227&amp;requiressl=yes&amp;pl=24&amp;gcr=za&amp;expire=1450535944&amp;lmt=1386308144932326&amp;key=yt6&amp;itag=5&amp;mime=video/x-flv&amp;ipbits=0&amp;dur=223.086&amp;ms=au&amp;fexp=9408541,9416126,9417353,9418204,9420452,9420539,9422596,9423299,9423662,9424551,9424623,9424771,9425308,9425514,9426036&amp;mv=m&amp;mt=1450514205&amp;mn
>  =sn-hfxc
>  -j2ul&amp;mm=31&amp;source=youtube&amp;sver=3&amp;upn=yRJxfxpPyB4&amp;signature=FCD3CD0E8008638075061AF2D323FA736A2161CD75A.2F340371EBB60DE6B2DC321E571866CA42E830E40E4&amp;ratebypass=yes&amp;title=Owl City feat. TobyMac - Light of Christmas _ New Song 2013 DYVAM - Info: itag18 url:https://r1---sn-hfxc-j2ul.googlevideo.com/videoplayback?sparams=dur,gcr,id,initcwndbps,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,pl,ratebypass,requiressl,source,upn,expire&amp;id=o-ANpa5umBrcQLUmRMBR3gK4IZzvCq0GkP-Pe2v4k5-pB8&amp;initcwndbps=307500&amp;ip=165.255.70.227&amp;requiressl=yes&amp;pl=24&amp;gcr=za&amp;expire=1450535944&amp;mn=sn-hfxc-j2ul&amp;lmt=1417222227576870&amp;key=yt6&amp;itag=18&amp;mime=video/mp4&amp;ipbits=0&amp;dur=223.097&amp;ms=au&amp;fexp=9408541,9416126,9417353,9418204,9420452,9420539,9422596,9423299,9423662,9424551,9424623,9424771,9425308,9425514,9426036&amp;mv=m&amp;mt=14505142
>  05&a
>  mp;ratebypass=yes&amp;mm=31&amp;source=youtube&amp;sver=3&amp;upn=yRJxfxpPyB4&amp;signature=26F46F360298341C1B928172C78C3D1D1ABFC1D8CDE.0D6988B31F4B16D2EAA408E54E99FC9D0673FFF6FF6&amp;title=Owl City feat. TobyMac - Light of Christmas _ New Song 2013 DYVAM - Info: itag22 url:https://r1---sn-hfxc-j2ul.googlevideo.com/videoplayback?sparams=dur,gcr,id,initcwndbps,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,pl,ratebypass,requiressl,source,upn,expire&amp;id=o-ANpa5umBrcQLUmRMBR3gK4IZzvCq0GkP-Pe2v4k5-pB8&amp;initcwndbps=307500&amp;ip=165.255.70.227&amp;requiressl=yes&amp;pl=24&amp;gcr=za&amp;expire=1450535944&amp;mn=sn-hfxc-j2ul&amp;lmt=1417222232096005&amp;key=yt6&amp;itag=22&amp;mime=video/mp4&amp;ipbits=0&amp;dur=223.097&amp;ms=au&amp;fexp=9408541,9416126,9417353,9418204,9420452,9420539,9422596,9423299,9423662,9424551,9424623,9424771,9425308,9425514,9426036&amp;mv=m&amp;mt=1450514205&amp;
>  ratebypa
>  ss=yes&amp;mm=31&amp;source=youtube&amp;sver=3&amp;upn=yRJxfxpPyB4&amp;signature=2A16A1233458C6149459D0BA36927641241B2C708BD.646027864979E328238304B1633C1141ECC88D3CD3C&amp;title=Owl City feat. TobyMac - Light of Christmas _ New Song 2013 DYVAM fetch status 200 DYVAM - Info: signature start error DYVAM - Info: signaturefunction gr -- null ***null"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gantt/downloadyoutube/issues/64#issuecomment-165962541>
> .
>


-- 
Ionut Alex Chitu

**Comment by gantt** [comment]
Fixed in 1.8.5. I uploaded the extension to Mozilla, Opera and the script to Greasyfork. They're also available here: https://github.com/gantt/downloadyoutube
