### ISSUE TITLE
Not working in Firefox 43.0.2

### ISSUE THREAD

**Issue by Perkin5** [gantt/downloadyoutube#65]
When I attempt to download a youtube video, the whole screen goes white. Firefox has not crashed as I can use the back button but it looks as though there is a compatibility problem. Is a fix in prospect?

**Comment by gantt** [comment]
Complain to Mozilla. I uploaded a new version of the extension on Saturday.
4 days later, they still haven't reviewed it.

You can't even install extensions without being signed by Mozilla, so you
have to wait until they review each and every review. It's boring,
frustrating and annoying. I know it's almost Christmas and they're some
unpaid volunteers, but that's what it is.

On Wednesday, December 23, 2015, Perkin5 <notifications@github.com> wrote:

> When I attempt to download a youtube video, the whole screen goes white
> Firefox has not crashed as I can use the back button but it looks as though
> there is a compatibility problem Is a fix in prospect?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gantt/downloadyoutube/issues/65>.
>


-- 
Ionut Alex Chitu
http://googlesystem.blogspot.com

**Comment by Perkin5** [comment]
Thanks for the prompt response - I'll be patient and wait!

Mike

**Comment by gantt** [comment]
For now, you can only install it by disabling signature verification (go to about:config, ignore the warning, search for xpinstall.signatures.required and change the value from true to false) and then downloading version 1.8.5: https://addons.mozilla.org/en-US/firefox/addon/download-youtube/versions/

**Comment by gantt** [comment]
Another option: Greasemonkey + this script: https://greasyfork.org/en/scripts/1317-download-youtube-videos-as-mp4

**Comment by Perkin5** [comment]
Yeah - that did it! Many thanks you excellent guy.

Mike
