### ISSUE TITLE
Some Vidoes bring blank screen

### ISSUE THREAD

**Issue by quadragin** [gantt/downloadyoutube#66]
Some Videos will not download takes me out of you tube to this:
https://r3---sn-a5mekn7k.googlevideo.com/videoplayback?ms=au&mime=video/mp4&mv=m&source=youtube&pl=22&id=o-ALAF6jmcDh9a2yo5IA8MhCvC3lGNSJxOF_8KDfr5_oZg&initcwndbps=748750&dur=5825.700&itag=18&mn=sn-a5mekn7k&ip=198.74.46.187&mm=31&expire=1451780281&mt=1451758515&ipbits=0&upn=EVgSSdOueuQ&lmt=1445930862604384&key=yt6&sparams=dur,gcr,id,initcwndbps,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,nh,pl,ratebypass,requiressl,source,upn,expire&nh=IgpwcjAyLmxheDAyKgkxMjcuMC4wLjE&sver=3&requiressl=yes&gcr=us&ratebypass=yes&fexp=9416126,9420452,9422596,9423662&signature=AC2FC20BE66DFFE57740B1D893316EEF7E388B72D79.B76B9087CB56A6E9ADA64313C51EF3FC62351829829&title=Red%20Greatest%20Hits
Other Videos download just fine... Everything has been awesome until this morning.

**Comment by gantt** [comment]
Update to the latest version 1.8.5.

On Saturday, January 2, 2016, quadragin <notifications@github.com> wrote:

> Some Videos will not download takes me out of you tube to this:
>
> https://r3---sn-a5mekn7kgooglevideocom/videoplayback?ms=au&mime=video/mp4&mv=m&source=youtube&pl=22&id=o-ALAF6jmcDh9a2yo5IA8MhCvC3lGNSJxOF_8KDfr5_oZg&initcwndbps=748750&dur=5825700&itag=18&mn=sn-a5mekn7k&ip=1987446187&mm=31&expire=1451780281&mt=1451758515&ipbits=0&upn=EVgSSdOueuQ&lmt=1445930862604384&key=yt6&sparams=dur,gcr,id,initcwndbps,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,nh,pl,ratebypass,requiressl,source,upn,expire&nh=IgpwcjAyLmxheDAyKgkxMjcuMC4wLjE&sver=3&requiressl=yes&gcr=us&ratebypass=yes&fexp=9416126,9420452,9422596,9423662&signature=AC2FC20BE66DFFE57740B1D893316EEF7E388B72D79B76B9087CB56A6E9ADA64313C51EF3FC62351829829&title=Red%20Greatest%20Hits
> Other Videos download just fine Everything has been awesome until this
> morning
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gantt/downloadyoutube/issues/66>.
>


-- 
Ionut Alex Chitu
http://googlesystem.blogspot.com
