### ISSUE TITLE
Can't download these videos?

### ISSUE THREAD

**Issue by lindongbin** [gantt/downloadyoutube#67]
https://www.youtube.com/watch?v=aazWYaBqjtE
https://www.youtube.com/watch?v=YFr6p7vB9hc

**Comment by aragond** [comment]
ditto and I am getting a LOT of youtube now that won't let me download for the same reasons. I haven't been keeping tabs, but I know these from this morning:
https://www.youtube.com/watch?v=qhDO3CoAZks
https://www.youtube.com/watch?v=xGav-z5yRiU
https://www.youtube.com/watch?v=0rtV5esQT6I
https://www.youtube.com/watch?v=kUGQ7Tz4os0
and yet there's a truckload more than I can download from. Weird.
v1.8.4 on Firefox 43.0.3 on Windows 7 up-to-date-with-patches

**Comment by gantt** [comment]
Update to 1.8.5

On Monday, January 4, 2016, aragond <notifications@github.com> wrote:

> ditto and I am getting a LOT of youtube now that won't let me download for
> the same reasons. I haven't been keeping tabs, but I know these from this
> morning:
> https://www.youtube.com/watch?v=qhDO3CoAZks
> https://www.youtube.com/watch?v=xGav-z5yRiU
> https://www.youtube.com/watch?v=0rtV5esQT6I
> https://www.youtube.com/watch?v=kUGQ7Tz4os0
> and yet there's a truckload more than I can download from. Weird.
> v1.8.4 on Firefox 43.0.3 on Windows 7 up-to-date-with-patches
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gantt/downloadyoutube/issues/67#issuecomment-168596572>
> .
>


-- 
Ionut Alex Chitu
http://googlesystem.blogspot.com

**Comment by lindongbin** [comment]
thanks!
