### ISSUE TITLE
"Request to cross origin resource" warning in Tampermonkey 

### ISSUE THREAD

**Issue by narcolepticinsomniac** [gantt/downloadyoutube#74]
Tampermonkey updated recently so that may be the reason. It pops open a warning tab on pretty much every Youtube video page opened (see pic). Clicking "always allow" doesn't seem to prevent it.

![2016-04-07_03-14-57](https://cloud.githubusercontent.com/assets/14100003/14343624/3d81aed4-fc70-11e5-888a-91dd99143f5a.jpg)

**Comment by gantt** [comment]
Update the script to the latest version. I fixed this issue a few months
ago.

**Comment by narcolepticinsomniac** [comment]
Thanks. I did check the version # before posting and the one installed matched the current 1.8.7. Either way, uninstalling/reinstalling resolved it. 

Great script btw, keep up the good work.
