### ISSUE TITLE
signature decoding broken again

### ISSUE THREAD

**Issue by raszpl** [gantt/downloadyoutube#77]
worked after december fix for a while, but broken again
example non working link
https://www.youtube.com/watch?v=1Fpk5RUa4kI
youtube-dl decodes it fine

**Comment by gantt** [comment]
Works fine here. Can you send this?

https://github.com/gantt/downloadyoutube/blob/master/Debug.md

**Comment by raszpl** [comment]
"DYVAM - Info: Standard mode. videoID 1Fpk5RUa4kI;  DYVAM - Info: url https://www.youtube.com/watch?v=1Fpk5RUa4kI; useragent Opera/9.80 (Windows NT 6.2; WOW64) Presto/2.12.388 Version/12.18 DYVAM fetch https://s.ytimg.com/yts/jsbin/player-en_GB-vflxgfRyq/base.js DYVAM - Info: itag5 url:https://r1---sn-f5f7ln7s.googlevideo.com/videoplayback?initcwndbps=2478750&amp;fexp=9405972,9416126,9416891,9417580,9422596,9423965,9428398,9431012,9433096,9433656,9433776,9433946,9434016,9435036,9435527,9435876,9436011,9436825,9437067,9437566,9437681,9437732&amp;expire=1464405384&amp;upn=zOxLprW_ORY&amp;key=yt6&amp;mime=video/x-flv&amp;ms=au&amp;mv=m&amp;mt=1464383592&amp;id=o-AL-hgTZPqGHUQDzSXM4cO5KSbtqWTLJItMVhAGMURQ0G&amp;pl=16&amp;ipbits=0&amp;mn=sn-f5f7ln7s&amp;mm=31&amp;ip=31.178.207.150&amp;gcr=pl&amp;sparams=dur,gcr,id,initcwndbps,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,nh,pl,requiressl,source,upn,expire&amp;requiressl=yes&amp;source=youtube&amp;dur=275.827&amp;lmt=1464268305836149&amp;itag=5&amp;nh=IgpwcjAyLndhdzAyKgkxMjcuMC4wLjE&amp;sver=3&amp;signature=83D3AB7B3DDE45243CFC3C42ED9767D7914BDD26BD.9D3255DCED2B305C00F2CF74C1D67E3298623710&amp;ratebypass=yes&amp;title=Deus Ex Mankind Divided Live Action Trailer (PS4_Xbox One) 2016 DYVAM - Info: itag18 url:https://r1---sn-f5f7ln7s.googlevideo.com/videoplayback?initcwndbps=2478750&amp;fexp=9405972,9416126,9416891,9417580,9422596,9423965,9428398,9431012,9433096,9433656,9433776,9433946,9434016,9435036,9435527,9435876,9436011,9436825,9437067,9437566,9437681,9437732&amp;expire=1464405384&amp;upn=zOxLprW_ORY&amp;key=yt6&amp;mime=video/mp4&amp;ms=au&amp;mv=m&amp;mt=1464383592&amp;id=o-AL-hgTZPqGHUQDzSXM4cO5KSbtqWTLJItMVhAGMURQ0G&amp;pl=16&amp;ipbits=0&amp;mn=sn-f5f7ln7s&amp;mm=31&amp;ip=31.178.207.150&amp;gcr=pl&amp;sparams=dur,gcr,id,initcwndbps,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,nh,pl,ratebypass,requiressl,source,upn,expire&amp;requiressl=yes&amp;source=youtube&amp;dur=275.853&amp;lmt=1464268306236541&amp;itag=18&amp;nh=IgpwcjAyLndhdzAyKgkxMjcuMC4wLjE&amp;ratebypass=yes&amp;sver=3&amp;signature=F3C39C22EA1626F76E7169A07CB56BF1DF7B5249E7.C96A8D1748681B2E50A8A67B37482B64CBC93E20&amp;title=Deus Ex Mankind Divided Live Action Trailer (PS4_Xbox One) 2016 DYVAM - Info: itag22 url:https://r1---sn-f5f7ln7s.googlevideo.com/videoplayback?initcwndbps=2478750&amp;fexp=9405972,9416126,9416891,9417580,9422596,9423965,9428398,9431012,9433096,9433656,9433776,9433946,9434016,9435036,9435527,9435876,9436011,9436825,9437067,9437566,9437681,9437732&amp;expire=1464405384&amp;upn=zOxLprW_ORY&amp;key=yt6&amp;mime=video/mp4&amp;ms=au&amp;mv=m&amp;mt=1464383592&amp;id=o-AL-hgTZPqGHUQDzSXM4cO5KSbtqWTLJItMVhAGMURQ0G&amp;pl=16&amp;ipbits=0&amp;mn=sn-f5f7ln7s&amp;mm=31&amp;ip=31.178.207.150&amp;gcr=pl&amp;sparams=dur,gcr,id,initcwndbps,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,nh,pl,ratebypass,requiressl,source,upn,expire&amp;requiressl=yes&amp;source=youtube&amp;dur=275.853&amp;lmt=1464268417866319&amp;itag=22&amp;nh=IgpwcjAyLndhdzAyKgkxMjcuMC4wLjE&amp;ratebypass=yes&amp;sver=3&amp;signature=C2F20EB53580CC68B62170CF8F60B8170418DE006D.8E2B7F222F9A96B9F517CAEF51DE422B6C0A0306&amp;title=Deus Ex Mankind Divided Live Action Trailer (PS4_Xbox One) 2016 ***null"

all three generated links produce HTTP/1.1 403 Forbidden

**Comment by gantt** [comment]
Thanks for sending the debug code.

It's hard to tell, but I suspect you're using an older version of the extension or script. Can you update to the latest version (1.8.5 for the Opera extension, 1.8.7 for the script)?

The main issue is that the URLs extracted from the code use the original encrypted signature, so they don't work. It's not clear if the script fails to download the JS file with decryption code or the script can't properly parse the file. You can't run the functions directly.

I checked the extension using Opera 12/Mac and it works fine. I get a different JS file, but the code is similar.

**Comment by raszpl** [comment]
figured it out. last time I was reinstalling windows I didnt bother reinstalling all the extensions, just copied them over from old drive. 
I had to uninstall extension, then manually delete 
AppData\Local\Opera\Opera x64\widgets\wuid-whatever left over, finally do a fresh install

old widgets\wuid-whatever directory was somehow preventing decoding from working ?!? while still making it look like extension was ok (Download button rendering fine, no js errors in debug console).
Its like something bad was cached in wuid directory :(

sorry for false report.
