### ISSUE TITLE
Download Button does not show on many videos

### ISSUE THREAD

**Issue by DavidManning** [gantt/downloadyoutube#79]
Download Button does not show on many videos, such as this one: https://www.youtube.com/watch?v=KXMUhnkj58k
Using latest Firefox. 
Some videos button shows, such as this one - https://www.youtube.com/watch?v=FZLr6mk-Eog -  but many it does not.
Both of the above videos were uploaded by same user.

**Comment by gantt** [comment]
It works for me.

![screen shot 2016-07-04 at 09 09 51](https://cloud.githubusercontent.com/assets/8141540/16552137/2e4c1e30-41c7-11e6-9ebc-4f04a4ff9b30.png)

Can you post some debug info for a video you can't download: https://github.com/gantt/downloadyoutube/blob/master/Debug.md ?

**Comment by FletchXYZ** [comment]
Working here, too.
![screenshot_66](https://cloud.githubusercontent.com/assets/5183850/16711962/ea00ed0e-463b-11e6-9572-8ff60254328a.png)

**Comment by DavidManning** [comment]
Solved it. Cookie problem my end. One too many add-ons.
Thanks for your help.
