### ISSUE TITLE
No 1080p dash video or audio links in format list?

### ISSUE THREAD

**Issue by Elite2016** [gantt/downloadyoutube#82]
This video has 1080p streaming support but no option for same in download menu - https://www.youtube.com/watch?v=VxEgGUBaXw4 there is no option for video only 1080p format. Why? :(

![sshot-6](https://cloud.githubusercontent.com/assets/21891256/18199485/0e3b9ffe-711e-11e6-8cab-265f58643ec2.png)
![sshot-5](https://cloud.githubusercontent.com/assets/21891256/18199492/132cffd0-711e-11e6-933d-dc6788d37570.png)

**Comment by Elite2016** [comment]
DEBUG INFO:

`"DYVAM - Info: Standard mode. videoID VxEgGUBaXw4;  DYVAM - Info: url https://www.youtube.com/watch?v=VxEgGUBaXw4; useragent Mozilla/5.0 (Windows NT 6.1; rv:48.0) Gecko/20100101 Firefox/48.0 DYVAM - Info: signature -3,2,-2,46,-1,31,27 //s.ytimg.com/yts/jsbin/player-en_US-vflqMMQzs/base.js DYVAM - Info: itag18 url:https://r3---sn-cnoa-w5pe.googlevideo.com/videoplayback?source=youtube&amp;upn=6Cl_xUp0eQw&amp;ei=y0fJV5S9FcuooAOYhonoAQ&amp;key=yt6&amp;ipbits=0&amp;pcm2cms=yes&amp;itag=18&amp;ms=au&amp;initcwndbps=138750&amp;mv=m&amp;dur=1685.791&amp;mt=1472808135&amp;id=o-ALT49tKro0Uw7nl7uqpfeqczlMRoibUIp-17IPPL8dhH&amp;sparams=dur,ei,id,initcwndbps,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,pcm2cms,pl,ratebypass,requiressl,source,upn,expire&amp;pl=21&amp;mn=sn-cnoa-w5pe&amp;ip=XXXXXXXX&amp;mm=31&amp;lmt=1472325682814333&amp;ratebypass=yes&amp;expire=1472830507&amp;sver=3&amp;mime=video/mp4&amp;requiressl=yes&amp;signature=7DDCA236D51DBA20219C2A8DF809C8C389454298.8D304460AEC5019C88F9520EE3838C73B39FA08F&amp;title=American Football @ The Wrecking Ball ATL 2016-8-14 (multicam) DYVAM - Info: itag22 url:https://r3---sn-cnoa-w5pe.googlevideo.com/videoplayback?source=youtube&amp;upn=6Cl_xUp0eQw&amp;ei=y0fJV5S9FcuooAOYhonoAQ&amp;key=yt6&amp;ipbits=0&amp;pcm2cms=yes&amp;itag=22&amp;ms=au&amp;initcwndbps=138750&amp;mv=m&amp;dur=1685.791&amp;mt=1472808135&amp;id=o-ALT49tKro0Uw7nl7uqpfeqczlMRoibUIp-17IPPL8dhH&amp;sparams=dur,ei,id,initcwndbps,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,pcm2cms,pl,ratebypass,requiressl,source,upn,expire&amp;pl=21&amp;mn=sn-cnoa-w5pe&amp;ip=XXXXXXXX&amp;mm=31&amp;lmt=1472332755804504&amp;ratebypass=yes&amp;expire=1472830507&amp;sver=3&amp;mime=video/mp4&amp;requiressl=yes&amp;signature=AE618DDA409B7C02B8E39ED9944E3BC1CB173AAA.9495D11E0B14AAC31492FBC5F4087AE4B452DF31&amp;title=American Football @ The Wrecking Ball ATL 2016-8-14 (multicam) DYVAM - Info: manifestURL https://manifest.googlevideo.com/api/manifest/dash/source/youtube/upn/6Cl_xUp0eQw/signature/62768A856380629605650AD2E4568A3542D275A5.B738AC74447CF8614A9C7D6DEC8910C6A7ED1555/ei/y0fJV5S9FcuooAOYhonoAQ/playback_host/r3---sn-cnoa-w5pe.googlevideo.com/sver/3/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/pcm2cms/yes/itag/0/ms/au/initcwndbps/138750/mv/m/mt/1472808135/id/o-ALT49tKro0Uw7nl7uqpfeqczlMRoibUIp-17IPPL8dhH/sparams/as%2Cei%2Chfr%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cplayback_host%2Crequiressl%2Csource%2Cexpire/hfr/1/pl/21/mn/sn-cnoa-w5pe/ip/XXXXXXXX/mm/31/ipbits/0/expire/1472830507/key/yt6/requiressl/yes DYVAM - Info: matchURL null ***null"`

**Comment by gantt** [comment]
Thanks for your bug report. 

The explanation is that the script only extracts URLs from the source code of the page. Dash URLs are usually included in both the source code and a separate file, but for some videos they're only added to the manifest. 

I've edited the code to address this issue, but I still need to test it before uploading it. If you find similar videos, please let me know.

**Comment by gantt** [comment]
Fixed in 1.8.8. If you're using the script, the new version is available here: https://greasyfork.org/en/scripts/1317-download-youtube-videos-as-mp4 If you're using the Firefox or Opera extensions, you'll have to wait until they're reviewed (hopefully, it won't take more than a few days).

Thanks again for bringing up this issue. If you ever find other bugs, please let me know.
